# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main"
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest, windows-latest,
	

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          - ad: Setup Go ortamı
   kullanımlar: action/setup-go@v3.5.0
   ile:
     # İndirmek (gerekirse) ve kullanmak için Go sürümü.  Semver özelliklerini ve aralıklarını destekler.
     go-versiyonu: # isteğe bağlı
     # go.mod veya go.work dosyasının yolu.
     go-versiyon dosyası: # isteğe bağlı
     # Eylemin her zaman sürüm spesifikasyonunu karşılayan mevcut en son sürümü kontrol etmesini istiyorsanız bu seçeneği true olarak ayarlayın
     en son kontrol: # isteğe bağlı
     # Geçiş sürümlerinden düğüm dağıtımlarını çekmek için kullanılır.  Bir varsayılan olduğu için, bu genellikle kullanıcı tarafından sağlanmaz.  Bu eylemi github.com'da çalıştırırken, varsayılan değer yeterlidir.  GHES üzerinde çalışırken, hız sınırlaması yaşıyorsanız github.com için kişisel bir erişim belirteci iletebilirsiniz.
     belirteç: # isteğe bağlı, varsayılan ${{ github.server_url == 'https://github.com' && github.token ||  '' }}
     # Önbelleğe almanın gerekli olup olmadığını belirtmek için kullanılır.  Önbelleğe almayı etkinleştirmek istiyorsanız, true olarak ayarlayın.
     önbellek: # isteğe bağlı
     # Bir bağımlılık dosyasının yolunu belirtmek için kullanılır - go.sum
     önbellek bağımlılığı yolu: # isteğe bağlı
     # Go kullanmak için hedef mimari.  Örnekler: x86, x64.  Varsayılan olarak sistem mimarisini kullanır.
     mimari: # isteğe bağlı 
		 - ad: Java JDK Kurulumu
   kullanımlar: action/setup-java@v3.9.0
   ile:
     # Ayarlanacak Java sürümü.  Tam veya semver Java sürümünü alır.  README dosyasında desteklenen sözdizimi örneklerine bakın
     java sürümü: # isteğe bağlı
     # `.java-version` dosyasının yolu.  README dosyasında desteklenen sözdizimi örneklerine bakın
     java sürümü dosyası: # isteğe bağlı
     # Java dağıtımı.  README dosyasındaki desteklenen dağıtımların listesine bakın
     dağıtım: 
     # Paket türü (jdk, jre, jdk+fx, jre+fx)
     java paketi: # isteğe bağlı, varsayılan jdk'dir
     # Paketin mimarisi (varsayılan olarak action runner'ın mimarisine göredir)
     mimari: # isteğe bağlı
     # Sıkıştırılmış JDK'nın bulunduğu yerin yolu
     jdkFile: # isteğe bağlı
     # Eylemin, sürüm spesifikasyonunu karşılayan mevcut en son sürümü kontrol etmesini istiyorsanız bu seçeneği ayarlayın
     en son kontrol: # isteğe bağlı
     # pom.xml dosyasındaki DistributionManagement havuzunun kimliği.  Varsayılan "github"
     sunucu kimliği: # isteğe bağlı, varsayılan github'dur
     # Apache Maven deposunda kimlik doğrulama için kullanıcı adı için ortam değişkeni adı.  Varsayılan $GITHUB_ACTOR'dur
     sunucu-kullanıcı adı: # isteğe bağlı, varsayılan GITHUB_ACTOR
     # Apache Maven deposunda kimlik doğrulaması için parola veya belirteç için ortam değişkeni adı.  Varsayılan $GITHUB_TOKEN'dir
     sunucu şifresi: # isteğe bağlı, varsayılan GITHUB_TOKEN'dir
     # settings.xml dosyasının yazılacağı yol.  Varsayılan ~/.m2'dir.
     ayarlar yolu: # isteğe bağlı
     # Varsa settings.xml dosyasının üzerine yazın.  Varsayılan "true"dur.
     üzerine yazma ayarları: # isteğe bağlı, varsayılan doğrudur
     # İçe aktarılacak GPG özel anahtarı.  Varsayılan boş dizedir.
     gpg-private-key: # isteğe bağlı
     # GPG özel anahtar parolası için ortam değişkeni adı.  Varsayılan $GPG_PASSPHRASE'dir.
     gpg parolası: # isteğe bağlı
     # Bağımlılıkları önbelleğe almak için derleme platformunun adı.  "maven", "gradle" veya "sbt" olabilir.
     önbellek: # isteğe bağlı
     # İş durumunu iş adımına geçirmek için geçici çözüm.  Bu değişken manuel ayar için tasarlanmamıştır
     iş durumu: # isteğe bağlı, varsayılan değer ${{ job.status }}
     # Microsoft Build of OpenJDK için olduğu gibi, github.com'da barındırılan sürüm bildirimlerini alırken kimlik doğrulaması yapmak için kullanılan belirteç.  Bu eylemi github.com'da çalıştırırken, varsayılan değer yeterlidir.  GHES üzerinde çalışırken, hız sınırlaması yaşıyorsanız github.com için kişisel bir erişim belirteci iletebilirsiniz.
     belirteç: # isteğe bağlı, varsayılan ${{ github.server_url == 'https://github.com' && github.token ||  '' }}
     # Varsayılan "${distribution}_${java-version}" adı istenmiyorsa, Maven Toolchain Kimliğinin adı.  Gelişmiş Kullanım dosyasında desteklenen sözdizimi örneklerine bakın
     mvn-toolchain-id: # isteğe bağlı
     # Varsayılan "${distribution}" adı istenmiyorsa, Maven Toolchain Satıcısının adı.  Gelişmiş Kullanım dosyasında desteklenen sözdizimi örneklerine bakın
     mvn-toolchain-vendor: # isteğe bağlı 
